# Labeler configuration for auto-labeling PRs based on changed files

backend:
  - backend/**/*

frontend:
  - frontend/**/*

ai-service:
  - ai-service/**/*

infrastructure:
  - infrastructure/**
  - .github/**
  - docker-compose*.yml
  - Dockerfile*

documentation:
  - '*.md'
  - 'docs/**/*'

config:
  - '**/.eslintrc*'
  - '**/.prettierrc*'
  - '**/tsconfig.json'
  - '**/package.json'
  - '**/requirements.txt'

